services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 33006:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080